# Generated by Django 6.0.3 on 2026-03-26 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quote', models.TextField(help_text='The exact statement being verified.')),
                ('text', models.TextField(help_text='Full explanation and verification details.')),
                ('author_name', models.CharField(max_length=255)),
                ('author_role', models.CharField(blank=True, max_length=255)),
                ('read_time_minutes', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('in_progress', 'In Progress'), ('true', 'True'), ('false', 'False'), ('misleading', 'Misleading'), ('unverifiable', 'Unverifiable')], default='unverified', max_length=20)),
                ('tags', models.ManyToManyField(blank=True, to='verification.tag')),
            ],
        ),
    ]
